# Generated by Django 2.2.17 on 2021-10-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='update_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
